language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"

services:
  - postgresql

install: travis_retry pip install coveralls tox-travis

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: tox

after_success:
  - coveralls